### ISSUE TITLE
Move sources to an uber mono-repository

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-planning#230]
Moving content from https://docs.google.com/document/d/1kPEzs5BLCQZlV5wPiSUv3GW7DfaCwwD3W3QieeawnDs/edit#heading=h.w4bqbhke4dcx to here.

What?
=====

The idea is to reside all sources in a single uber mono-repository, that will allow us to tag releases and introduce new features uniformly. The CI jobs would need to be adjusted.

How?
====
The repositories that would need to be merged are: 

- [x] launcher-frontend
- [x] launcher-backend
- [ ] launcher-booster-catalog-service
- [x] launcher-creator-backend
- [ ] launcher-operator
- [x] launcher-openshift-templates
- ~~launcher-vscode-extension~~  (will be moved to the https://github.com/redhat-developer org)

**Comment by quintesse** [comment]
Added the launcher-booster-catalog-service to the list above.

**Comment by gastaldi** [comment]
In this issue, we must create the same Docker images and keep the same deployment template. 
Unification of services and simplification of the deployment template/script should happen in a separate issue.

**Comment by gastaldi** [comment]
Done. the Launcher-booster-catalog-service and the operator will remain in separate repositories for now
