### ISSUE TITLE
Leverage Chefile in fabric8 boosters

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-planning#94]
Launcher backlog for https://github.com/openshiftio/openshift.io/issues/1318

## Goal
Anyone who is using Launcher (from standalone or from its integration within OSIO) will be able to get a developer workspace in Che fully ready and configured to work on the generated project (boosters).

## Description
When a user is using Launcher, he is selecting a booster which is then uploaded on a git repository. We want to provide the associated Chefile with the booster so that it provides a ready-to-use definition of a developer workspace in Che.

The Chefile will provide the information about the workspace’s runtime that is needed, as well as all the information that are needed to build, run and debug on the project.

Note: This Chefile will work only with Che installed on kubernetes/openshift. 

## Subtasks
Along with the work we are doing on upstream Che : https://github.com/eclipse/che/issues/4362

- [ ] Handle Chefile for different infrastructure implementation
- [ ] Provide Chefile for all boosters provided with fabric-8 Launcher
- [ ] Add instructions to start developer workspace in Che, in the readme.md of the booster
- [ ] Add instructions to start developer workspace in Che, in the readme.md of the generated source code from fabric8 launcher.

**Comment by bartoszmajsak** [comment]
@gastaldi let's sync if you plan to work on that.

**Comment by ALRubinger** [comment]
Another item to add into the Booster Governance Process.

**Comment by rdruss** [comment]
Any chance that the launcher team may look at this issue for just Che support (i.e. move the openshift.io part to a separate issue)?  What about not just for boosters, but for new (generated) applications as well?

**Comment by gastaldi** [comment]
Should we work on having a Chefile or generate the Devfile as specified in https://github.com/eclipse/che/issues/11549 ? @gorkem can you share a light here?

**Comment by gastaldi** [comment]
Superseded by #209
